<script>
    $(document).ready(function(){
        $("a").click(function(evento){
            //$("#vista").css("display","block");
            $("#vista").show("normal");
        })
    });
    
    $(document).ready(function(){
        $("a").click(function(evento){
            <?php $auth = Zend_Auth::getInstance();
                if($auth->hasIdentity()){
                    $sesion = 1;  
                }
                else{
                    $sesion = 0;
                }?>
        
            var sesion = <?php echo $sesion;?>;
        
            if(sesion==1){
                $("#logout").css("display", "block")
            }
            else{
                $("#logout").css("display", "none")
            }    
        })
    });
    
    $(document).ready(function(){
        <?php $auth1 = Zend_Auth::getInstance();
                if($auth1->hasIdentity()){
                    $sesion = 1;  
                }
                else{
                    $sesion = 0;
                }?>
        
            var sesion = <?php echo $sesion;?>;
        
            if(sesion==1){
                $("#logout").css("display", "block")
            }
            else{
                $("#logout").css("display", "none")
            }
    })
</script>

<div id="menu" style="font-weight: bold; background-color: #8ea3ae; padding-top: 10px; padding-bottom: 5px; border-bottom-left-radius: 5px; border-bottom-right-radius: 5px">
    <nav>
        <ul>
            <a href="<?php echo $this->url(array('controller'=>'reporte','action'=>'buscar')); ?>" target="vista">Abrir Reportes  </a>
            <a href="<?php echo $this->url(array('controller'=>'reporte','action'=>'crear')); ?>" target="vista">|  Crear Reportes</a>
            <a id="logout" style="display: none" href="<?php echo $this->url(array('controller'=>'perfil','action'=>'logout')); ?>" target="vista">Salir Sesión</a>
        </ul>
    </nav>
</div>

<div id="vista" style="display: none">
    <table class="tabla_datos" width="100%" border="0" cellpadding="1" cellspacing="1">
        <tr valign="top" height="500px">
            <td width="100%" height="100%" style="height: 100%">
                <iframe name="vista" src="" width="100%" height="100%"></iframe>
            </td>
        </tr>
    </table>    
</div>