<script>
    $(document).ready(function(){
//        $("a").mouseover(function(evento){
//            $("#menu").css("backgroundColor","blue");
//            //alert("hola");
//            //evento.preventDefault();
//        })
//        
//        $("a").mouseout(function(evento){
//            $("#menu").css("backgroundColor" , "orangered");
//        })
        
        $("a").click(function(evento){
            $("#vistaCarga").show("fast");
        })
    })
</script>

<div id="menu" style="background-color: #4b84c7; padding: 2px; font-weight: bold">
    <ul>
        <li><a href="<?php echo $this->url(array('controller'=>'reporte','action'=>'buscar')); ?>" target="vista">Abrir Reportes</a></li>
        <li><a href="<?php echo $this->url(array('controller'=>'reporte','action'=>'crear')); ?>" target="vista">Crear Reportes</a></li>
        
        <?php $auth = Zend_Auth::getInstance();
        if ($auth->hasIdentity()) : ?>
        <li>Perfil:<?php echo $auth->getIdentity(); ?> </li>
        <li><a href="<?php echo $this->url(array('controller'=>'perfil','action'=>'logout')); ?>" target="vista">Salir del Perfil</a></li>
        
        <?php else: ?>
        <li><a href="<?php echo $this->url(array('controller'=>'perfil','action'=>'login')); ?>" target="vista">Ingresar a Perfil</a></li>
        
        <?php endif; ?>
    </ul>
</div>

<div id="vistaCarga" style="display: none">
<table class="tabla_datos" width="100%" border="0" cellpadding="1" cellspacing="1">
    <tr height=300px" valign="top">
        <td height="100%" style="height:100%;" colspan="3">
        <iframe name="vista" src="" width="100%" height="100%"></iframe>
        </td>
    </tr>
</table>
</div>