<div>
    <ul>
        <li><a href="/reporte/buscar" target="vista">Abrir Reportes</a></li>
        <li><a href="/reporte/crear" target="vista">Crear Reportes</a></li>
        <?php 
        $auth = Zend_Auth::getInstance();
        if ($auth->hasIdentity()) : ?>
        
        <li>Perfil:<?php echo $auth->getIdentity(); ?> </li>
        <li><a href="/perfil/logout" target="vista">Salir del Perfil</a></li>
        
        <?php else: ?>
        
        <li><a href="/perfil/login" target="vista">Ingresar a Perfil</a></li>
        
        <?php endif; ?>
                    
    </ul>
<table class="tabla_datos" width="100%" border="0" cellpadding="1" cellspacing="1">
    <tr height=300px" valign="top">
        <td height="100%" style="height:100%;" colspan="3">
        <iframe name="vista" src="" width="100%" height="100%">No</iframe>
        </td>
    </tr>
</table>
</div>