<div id="contenido">
    <table id="dg_detalle2" class="tabla_datos" width="100%" cellpadding="1" cellspacing="1">
        <thead>
            <tr>
                <th class="cabecera" align="center" width="40%">Nombre del Reporte</th>
                <th class="cabecera" align="center" width="12%">Fecha de Creación</th>
                <th class="cabecera" align="center" width="30%">Nombre del Solicitante</th>
                <th class="cabecera" align="center" width="5%"></th>
                <th class="cabecera" align="center" width="5%"></th>
            </tr> 
        </thead>
         <tbody>
         <?php 
         if(count($this->reportes)) :
         foreach ($this->reportes as $reporte) :
         //Aquí hacemos el filtro para mostrar solo los reportes correspondientes al usuario
         if($reporte->PERFIL_ID == $this->idUserActual):
         ?>
            <tr>             
                <td class="contenido" align="left"><?php echo $reporte->REPORTES_NOMBRE; ?></td>
                <td class="contenido" align="center"><?php echo $reporte->REPORTES_FECHA; ?></td>
                <td class="contenido" align="center"><?php echo $reporte->REPORTES_SOLICITANTE; ?></td>
                <td class="contenido" align="center"><a href="<?php echo $this->url(array('controller'=>'reporte','action'=>'usar','reporte_id'=>$reporte->REPORTES_ID)); ?>">Ver</a></td>
                <td class="contenido" align="center"><a href="<?php echo $this->url(array('controller'=>'reporte','action'=>'eliminar','reporte_id'=>$reporte->REPORTES_ID)); ?>">Eliminar</a></td>
            </tr>
         
         <?php 
         endif; 
         endforeach;
         else:
         ?>
         
         <tr>
             <td colspan="5" align="center">No hay Datos!</td>
         </tr>
         
         <?php endif;?>
         </tbody>
    </table>
</div>