<script language="javascript">
    function crearDataGrid()
    {
        {
            var objTab = document.getElementById("dg_detalle2");
            dg = new DataGrid(objTab,
            {
                rowOver         : true,
                rowSelect       : true,
                rowMultiSelect  : false
                //onChangeSelect : verDetalle,
                //sortColumn	   : Array("N","S","N","N","N","N","N","N","N")
                }
            );
                var d = dg.getSelectedRow;
            }
    }
    window.onload = crearDataGrid;
</script>
<div id="contenido">
<form name="formulario" id="formulario">
<table id="dg_detalle2" class="tabla_datos" width="100%" border="0" cellpadding="1" cellspacing="1">
    <thead>
        <tr>
            <th class="cabecera" align="center" width="40%">Nombre del Reporte</th>
            <th class="cabecera" align="center" width="12%">Fecha de Creación</th>
            <th class="cabecera" align="center" width="30%">Nombre del Solicitante</th>
            <th class="cabecera" align="center" width="5%"></th>
            <th class="cabecera" align="center" width="5%"></th>
        </tr>
     </thead>
     <tbody>
         
         <?php foreach ($this->perfil as $perfil): ?>
         <?php if($perfil->Perfil_nombre == $this->name): ?>
         <?php $id = $perfil->Perfil_id; ?>
         <?php endif; ?>
         <?php endforeach; ?>
         
         <?php if(count($this->contenidoBusqueda)) :?>
         <?php foreach ($this->contenidoBusqueda as $contenido) :?>
         <?php if($contenido->Perfil_id == $id): ?>

         <tr>             
             <td class="contenido" align="left"><a href="/reporte/usar/reporte_id/<?php echo $contenido->Reporte_id; ?>"><?php echo $contenido->Reporte_nombre; ?></a></td>
             <td class="contenido" align="center"><?php echo $contenido->Reporte_fecha; ?></td>
             <td class="contenido" align="center"><?php echo $contenido->Reporte_solicitante; ?></td>
             <td class="contenido" align="center"><a href="/reporte/usar/reporte_id/<?php echo $contenido->Reporte_id; ?>">Ver</a></td>
             <td class="contenido" align="center"><a href="/reporte/eliminar/reporte_id/<?php echo $contenido->Reporte_id; ?>">Eliminar</a></td>
         </tr>
         
         <?php endif; ?>
         <?php endforeach; ?>
         <?php else :?>
         <tr>
             <td colspan="5" align="center">No hay Datos!</td>
         </tr>
         <?php endif;?>         
    </tbody>
</table>
</form>
</div>