<div>
<table>
    <p align="center">¿Está seguro que desea borrar el siguiente reporte?</p>
    <p align="center"><b><?php echo $this->model['reporte_nom']; ?></b></p>
    
    <form action="/reporte/eliminar" method="post">
        <div>
            <input type="hidden" name="reporte_id" value="<?php echo $this->model['reporte_id']; ?>"/>
            <input type="submit" name="eliminar" value="Si" />
            <input type="submit" name="eliminar" value="No" />
        </div>        
    </form>
</table>
</div>