<form action="<?php $this->url(array('controller'=>'reporte','action'=>'gestionar')); ?>">
    <div style="border-top-left-radius: 10px; border-top-right-radius: 10px;margin-top: 20px;margin: 0px 20px;text-align: center;background-color: #bbd4e1">
        <h3 style="text-align: right;padding: 10px">Editando Reporte N° <?php echo $this->reporte->Reporte_id; ?></h3> 
        <span style="font-weight: bold">Nombre del Reporte: </span><input size="40" type="text" name="nombre" value="<?php echo $this->reporte->Reporte_nombre; ?>">
        <span style="font-weight: bold">Nombre del Solicitante: </span><input size="40" type="text" name="solicitante" value="<?php echo $this->reporte->Reporte_solicitante; ?>">
    </div>

    <div style="border-bottom-left-radius: 10px; border-bottom-right-radius: 10px;margin-bottom: 20px;margin: 0px 20px;font-size: large; text-align: center;background-color: #bbd4e1">
        <br/>
        Aquí va lo que falta!
        <br/>    
    </div>
    <div style="padding-top: 20px;text-align: center">
        <input type="submit" name="boton" value="Grabar">
        <input type="button" name="cancelar" value="Cancelar">
    </div>
</form>