<script>
$(document).ready(function(){
    $("#selectTablas").click()
})
</script>

<form action="<?php $this->url(array('controller'=>'reporte','action'=>'gestionar')); ?>" method="post">
    <div class="layoutTitulo">
        <h3>Editando Reporte N° <?php echo $this->reporte->Reporte_id; ?></h3>
    </div>
    <div class="layoutSuperior"></div>
    <div class="layoutMedio">
        <div class="layoutTexto">
            <b>Nombre del Reporte: </b><input size="30" type="text" name="nombre" value="<?php echo $this->reporte->Reporte_nombre; ?>">
            <b>Nombre del Solicitante: </b><input type="text" name="solicitante" value="<?php echo $this->reporte->Reporte_solicitante; ?>">
        </div>
    </div>
    <div class="layoutMedioIzq">
        <select id="selectTablas" name="tablas">
            <?php foreach ($this->tablas as $tablas):?>
            <option value="<?php echo $tablas->Tablas_id; ?>"><?php echo $tablas->Tablas_nombre; ?></option>
            <?php endforeach; ?>
        </select>
        <br/>
        <select multiple name="campos">
            <?php foreach ($this->tablas as $tablas): ?>
            <option><?php ;?></option>
            <?php endforeach; ?>
        </select>
    </div>
    <div class="layoutMedioDer">
        <table class="tabla_datos">
            <thead>
            <tr>
                <th>Cabecera 1</th>
                <th>Cabecera 2</th>
                <th>Cabecera 3</th>
            </tr>
            </thead>
            <tbody>
                <tr>
                    <td>contenido</td>
                    <td>contenido</td>
                    <td>contenido</td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="layoutInferior"></div>
    <div class="layoutBotonera">
        <input type="submit" name="submitButton" value="Grabar"/>
        <input type="submit" name="submitButton" value="Cancelar"/>
    </div>
</form>