<table height="100%" width="100%" class="tabla_datos">
    <tr>
        <td align="center"></td>
        <td align="center"><a href="/reporte/buscar" target="vista">Buscar</a></td>
    </tr>
    <tr height="100%" valign="top">
        <td height="100%" style="height:100%;" colspan="2">
        <iframe name="vista" src="/reporte/buscar" width="100%" height="100%">No</iframe>
        </td>
    </tr>
</table>