<!doctype html>
<html lang="es">
    <head>
        <title>Generador de Reportes Dinámicos</title>
        <meta charset="UTF-8">
        <link rel="stylesheet" type="text/css" href="/css/estilos.css" />
        <script src="/js/funciones_generales.js" type="text/javascript"></script>
        <script src="/js/jquery-1.7.1.min.js" type="text/javascript"></script>
    </head>
    <body style="margin: 0px;">
        <?php echo $this->layout()->content; ?>
    </body>
</html>